config/routes.rb
Rails.application.routes.draw do

  scope controller: :registrations do
    get 'registrations'  => :index, as: 'registration'
    get 'registrations/user'  => :user, as: 'registration_user'
    get 'registrations/customer'  => :customer, as: 'registration_customer'
    get 'registrations/admin'  => :admin, as: 'registration_admin'
    post 'registrations/user'  => :create_user, as: 'registrations_user'
    post 'registrations/customer'  => :create_customer, as: 'registrations_customer'
    post 'registrations/admin'  => :create_admin, as: 'registrations_admin'
  end
  get 'profile', to: 'profile#index', as: 'profile'
  resources :products, only: [:index, :show, :new, :create] do
    post 'purchase', on: :member
  end
  devise_for :users
  root 'products#index'
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}"  Traineeship
    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav
        li
          a href="#{products_path}"  Products
        -if can? :create, Product
          li
            a href="#{new_product_path}"  Add Product
      ul.nav.navbar-nav.navbar-right
        -if user_signed_in?
          = wellcome_name(current_user)
          li
            = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
        -else
          li
            = link_to 'Sign in', new_user_session_path
          li
            = link_to 'Sign up', registration_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Traineeship'
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/header'
    main[role="main"]
      == render 'layouts/messages'
      == yield